name: CI/CD Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -euo pipefail
            APP_DIR=/var/www/laravel

            # kalau folder belum ada, clone pertama kali
            if [ ! -d "$APP_DIR/.git" ]; then
              su mkdir -p "$APP_DIR"
              su chown -R "$USER":"$USER" "$APP_DIR"
              git clone https://github.com/khoirurrozikin86/needle.git "$APP_DIR"
            fi

            cd "$APP_DIR"
            git fetch origin main
            git reset --hard origin/main

            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            [ -f .env ] || cp .env.example .env || true
            php artisan key:generate || true
            php artisan migrate --force || true

            php artisan config:clear || true
            php artisan config:cache || true
            php artisan route:cache || true
            php artisan view:cache || true

            su chown -R www-data:www-data "$APP_DIR"
            su chmod -R 775 "$APP_DIR/storage" "$APP_DIR/bootstrap/cache"

            su systemctl reload php8.2-fpm || true
            su systemctl reload nginx || true
